// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_G0_J_UmJyQ2nd0cxm72hiJseLEF2S8',
    appId: '1:154102638237:web:fd470936c12c4aac0a5674',
    messagingSenderId: '154102638237',
    projectId: 'chat-49cad',
    authDomain: 'chat-49cad.firebaseapp.com',
    storageBucket: 'chat-49cad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdcceyPbABiF9seYthO61z-OsmKyUhbbE',
    appId: '1:154102638237:android:1a09406d35eeb8170a5674',
    messagingSenderId: '154102638237',
    projectId: 'chat-49cad',
    storageBucket: 'chat-49cad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSK-NHnMT1Hr3OV9-dRBfH35WsInrP8ws',
    appId: '1:154102638237:ios:29f19d89d0e3baa20a5674',
    messagingSenderId: '154102638237',
    projectId: 'chat-49cad',
    storageBucket: 'chat-49cad.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSK-NHnMT1Hr3OV9-dRBfH35WsInrP8ws',
    appId: '1:154102638237:ios:29f19d89d0e3baa20a5674',
    messagingSenderId: '154102638237',
    projectId: 'chat-49cad',
    storageBucket: 'chat-49cad.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_G0_J_UmJyQ2nd0cxm72hiJseLEF2S8',
    appId: '1:154102638237:web:ca1220ce8c5717120a5674',
    messagingSenderId: '154102638237',
    projectId: 'chat-49cad',
    authDomain: 'chat-49cad.firebaseapp.com',
    storageBucket: 'chat-49cad.firebasestorage.app',
  );
}
